name: Pypi Analysis on BigQuery

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9,12,16,18,21 * * *'

  workflow_dispatch:

env:
  folder: ./src/pypi

jobs:
  run-query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ivanildobarauna

      - name: Make script executable
        run: chmod +x ${{ env.folder }}/runner.sh

      - name: Run all SQL scripts
        run: ${{ env.folder }}/runner.sh
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    environment:
      name: pypi-analysis-executor
      url: https://lookerstudio.google.com/reporting/5ad2e105-8aba-4454-a2d1-9aac14d68ee8/page/YQ6oD
